const CATEGORY_ACTION_TYPES = {
  FETCH_ITUNES: 'FETCH_ITUNES',
  SET_SEARCH_PODCAST: 'SET_SEARCH_PODCAST',
  SET_FILTERED_PODCAST: 'SET_FILTERED_PODCAST',
  SET_SELECT_PODCAST: 'SET_SELECT_PODCAST',
  SET_SELECT_SINGLE_PODCAST: 'SET_SELECT_SINGLE_PODCAST',
  SET_PODCAST_CARD: 'SET_PODCAST_CARD',
  SET_PODCAST_DATA: 'SET_PODCAST_DATA',
};

export default CATEGORY_ACTION_TYPES;
